import type { Metadata } from "next";
import { Google_Sans, Bricolage_Grotesque } from "next/font/google";
import "./globals.css";

// const googleSans = Google_Sans({
//   variable: "--font-google-sans",
//   subsets: ["latin"],
// });

const bricolagueFont = Bricolage_Grotesque({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${bricolagueFont.className} antialiased`}
      >
        <main className="relative min-h-screen">
          {children}
        </main>
      </body>
    </html>
  );
}
